
language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install:
    - pip install -e ."[dev]"

script:
    - flake8 forks/*.py
    - flake8 test/*.py
    - pytest --cov=forks

deploy:
    provider: pypi
    username: __token__
    password:
        secure: xwmnYxBtBOV+m7NPQ/W6EaUlToYgqTah3SeUeknLnstx+lOCcs+NcOLJ+AQTH/AFeNwb3gAsk/EocvPSB5MQ6SbtbwvxRpP/diEx1pgit+ClRxNZzvJs0q0ftM4vFgX3EFVMIRGPYp0t8SUjW6VXi8X7qkfAcXYSZ5P0blH1sCEn7/EdW4uNdRs6+o1QBSYI1lgCoy5sHptYoHtbdqUhuhYvyMFvQPPJvYM1OnR2b9EsD1oR0dnJV7BOhcL6E/uLpiBbDS/z+aFz4kAE0Zc+cio9i01wn8+pOYenTi5W3s46C0r2upriF0Wwpr3EJ6qMGiE5EbU84mXkIcJQEWaSaKjMFzlH2zmRpoT8hmFogjYiGN31ZOx1FS3tx1fzB5qF0nHYLmu8zIZpwoWQxvn9cgUeqMqF5WsHkg4EYtm7o9iBPIPzDxGaiIeLW1uLjmDpUfmZuD77kj0REVkn6yivriQ571t9YYNbdGsJs7ZvCy/zoLgHg7NRYxMnyN9c+DwJHeg3UUfHSRt0JDwedzSWOy081j7+3WEPSCYmsEF8Ggoe+wbx0GR8BdPSOP9geb6NWZaIT4QTxtxq1pzb2aPxQEM41WQUjxOY2NnXNJ67YwKU8AXCgab5/Zz01oCdJdjwr9dZfjMzUmfh8gtWF+/3DAz0K7mX/LorKskJZ8zEt0I=
    on:
        tags: true
    skip_existing: true

after_success:
    - coveralls
